//
// Generated file, do not edit! Created by opp_msgtool 6.0 from lb_message.msg.
//

#ifndef __LB_MESSAGE_M_H
#define __LB_MESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class LBMessage;
/**
 * Class generated from <tt>lb_message.msg:2</tt> by opp_msgtool.
 * <pre>
 * message LBMessage
 * {
 *     int type; // 0 = Req, 1 = Resp
 *     int source;
 *     int destination;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class LBMessage : public ::omnetpp::cMessage
{
  protected:
    int type = 0;
    int source = 0;
    int destination = 0;
    int hopCount = 0;

  private:
    void copy(const LBMessage& other);

  protected:
    bool operator==(const LBMessage&) = delete;

  public:
    LBMessage(const char *name=nullptr, short kind=0);
    LBMessage(const LBMessage& other);
    virtual ~LBMessage();
    LBMessage& operator=(const LBMessage& other);
    virtual LBMessage *dup() const override {return new LBMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getType() const;
    virtual void setType(int type);

    virtual int getSource() const;
    virtual void setSource(int source);

    virtual int getDestination() const;
    virtual void setDestination(int destination);

    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LBMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LBMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline LBMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<LBMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __LB_MESSAGE_M_H

